// Store all possible tiles in an array of objects
// Each object has an unique name and a href to an image
export const TILES = [
  { name: 'stekepanne', src: './images/1.svg' },
  { name: 'hodetelefoner', src: './images/2.svg' },
  { name: 'gulrot', src: './images/3.svg' },
  { name: 'pokal', src: './images/4.svg' },
  { name: 'gitar', src: './images/5.svg' },
  { name: 'snømann', src: './images/6.svg' },
  { name: 'gris', src: './images/7.svg' },
  { name: 'ugle', src: './images/8.svg' },
  { name: 'chaplin', src: './images/9.svg' },
  { name: 'kake', src: './images/10.svg' },
  { name: 'hamburger', src: './images/11.svg' },
  { name: 'gammel mann', src: './images/12.svg' },
  { name: 'parasoll', src: './images/13.svg' },
  { name: 'palme', src: './images/14.svg' },
  { name: 'kuleramme', src: './images/15.svg' },
  { name: 'trekkspill', src: './images/16.svg' },
  { name: 'medalje', src: './images/17.svg' },
  { name: 'gondol', src: './images/18.svg' },
  { name: 'fly', src: './images/19.svg' },
  { name: 'vekkeklokke', src: './images/20.svg' },
  { name: 'rom-monster', src: './images/21.svg' },
  { name: 'romvesen', src: './images/22.svg' },
  { name: 'sykebil', src: './images/23.svg' },
  { name: 'anker', src: './images/24.svg' },
  { name: 'lastebil', src: './images/25.svg' },
  { name: 'forskrekket ansikt', src: './images/26.svg' },
  { name: 'bil', src: './images/27.svg' },
  { name: 'avocado', src: './images/28.svg' },
  { name: 'øks', src: './images/29.svg' },
  { name: 'tåteflaske', src: './images/30.svg' },
  { name: 'baby', src: './images/31.svg' },
  { name: 'søppelbøtte', src: './images/32.svg' },
  { name: 'hus', src: './images/33.svg' },
  { name: 'chili', src: './images/34.svg' },
  { name: 'tre', src: './images/35.svg' },
  { name: 'hjort', src: './images/36.svg' },
  { name: 'telefon', src: './images/37.svg' },
];
