// Store all possible tiles in an array of objects
// Each object has an unique name and a href to an image
export const TILES = [
  { name: 'stekepanne', src: './images/1.svg', image: null, isMatched: false },
  {
    name: 'hodetelefoner',
    src: './images/2.svg',
    image: null,
    isMatched: false,
  },
  { name: 'gulrot', src: './images/3.svg', image: null, isMatched: false },
  { name: 'pokal', src: './images/4.svg', image: null, isMatched: false },
  { name: 'gitar', src: './images/5.svg', image: null, isMatched: false },
  { name: 'snømann', src: './images/6.svg', image: null, isMatched: false },
  { name: 'gris', src: './images/7.svg', image: null, isMatched: false },
  { name: 'ugle', src: './images/8.svg', image: null, isMatched: false },
  { name: 'chaplin', src: './images/9.svg', image: null, isMatched: false },
  { name: 'kake', src: './images/10.svg', image: null, isMatched: false },
  { name: 'hamburger', src: './images/11.svg', image: null, isMatched: false },
  {
    name: 'gammel mann',
    src: './images/12.svg',
    image: null,
    isMatched: false,
  },
  { name: 'parasoll', src: './images/13.svg', image: null, isMatched: false },
  { name: 'palme', src: './images/14.svg', image: null, isMatched: false },
  { name: 'kuleramme', src: './images/15.svg', image: null, isMatched: false },
  { name: 'trekkspill', src: './images/16.svg', image: null, isMatched: false },
  { name: 'medalje', src: './images/17.svg', image: null, isMatched: false },
  { name: 'gondol', src: './images/18.svg', image: null, isMatched: false },
  { name: 'fly', src: './images/19.svg', image: null, isMatched: false },
  {
    name: 'vekkeklokke',
    src: './images/20.svg',
    image: null,
    isMatched: false,
  },
  {
    name: 'rom-monster',
    src: './images/21.svg',
    image: null,
    isMatched: false,
  },
  { name: 'romvesen', src: './images/22.svg', image: null, isMatched: false },
  { name: 'sykebil', src: './images/23.svg', image: null, isMatched: false },
  { name: 'anker', src: './images/24.svg', image: null, isMatched: false },
  { name: 'lastebil', src: './images/25.svg', image: null, isMatched: false },
  {
    name: 'forskrekket ansikt',
    src: './images/26.svg',
    image: null,
    isMatched: false,
  },
  { name: 'bil', src: './images/27.svg', image: null, isMatched: false },
  { name: 'avocado', src: './images/28.svg', image: null, isMatched: false },
  { name: 'øks', src: './images/29.svg', image: null, isMatched: false },
  { name: 'tåteflaske', src: './images/30.svg', image: null, isMatched: false },
  { name: 'baby', src: './images/31.svg', image: null, isMatched: false },
  {
    name: 'søppelbøtte',
    src: './images/32.svg',
    image: null,
    isMatched: false,
  },
  { name: 'hus', src: './images/33.svg', image: null, isMatched: false },
  { name: 'chili', src: './images/34.svg', image: null, isMatched: false },
  { name: 'tre', src: './images/35.svg', image: null, isMatched: false },
  { name: 'hjort', src: './images/36.svg', image: null, isMatched: false },
  { name: 'telefon', src: './images/37.svg', image: null, isMatched: false },
];
